#!/bin/bash
#SBATCH -J ITP
#SBATCH -o /workspace/shashank/pglistr_tumor/scripts/..//results/inv-128-noconsv//log
#SBATCH -p rebels
#SBATCH -N 1
#SBATCH -n 20
#SBATCH -t 100:00:00
source ~/.bashrc
export OMP_NUM_THREADS=1
mpirun /workspace/shashank/pglistr_tumor/scripts/..//build/last/inverse -nx 128 -ny 128 -nz 128 -beta 0 -multilevel 0 -inject_solution 0 -pre_reacdiff_solve 0 -rho_inversion 8 -k_inversion 0.01 -nt_inversion 50 -dt_inversion 0.02 -rho_data 8 -k_data 0.01 -nt_data 50 -dt_data 0.02 -regularization L1c -interpolation 0 -diffusivity_inversion 1 -reaction_inversion 1 -basis_type 1 -number_gaussians 64 -sigma_factor 1 -sigma_spacing 2 -testcase 0 -solve_rho_k 0 -gaussian_volume_fraction 0.99 -lambda_continuation 1 -target_sparsity 0.99 -sparsity_level 10 -threshold_data_driven 0.1 -sigma_data_driven 1 -output_dir /workspace/shashank/pglistr_tumor/scripts/..//results/inv-128-noconsv/ -newton_solver QN -line_search armijo -newton_maxit 50 -gist_maxit 2 -krylov_maxit 1 -rel_grad_tol 0.001 -syn_flag 0 -data_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/c_final.nc -gm_path /workspace/shashank/pglistr_tumor/scripts/..//brain_data/jakob/128/jakob_gm.nc -wm_path /workspace/shashank/pglistr_tumor/scripts/..//brain_data/jakob/128/jakob_wm.nc -csf_path /workspace/shashank/pglistr_tumor/scripts/..//brain_data/jakob/128/jakob_vt.nc -glm_path /workspace/shashank/pglistr_tumor/scripts/..//brain_data/jakob/128/jakob_csf.nc -p_gm_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/gm_final.nc -p_wm_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/wm_final.nc -p_csf_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/vt_final.nc -p_glm_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/csf_final.nc -z_cm 128 -y_cm 76 -x_cm 112 -obs_mask_path  -support_data_path  -gaussian_cm_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/phi-mesh-forward.txt -pvec_path /workspace/shashank/pglistr_tumor/scripts/..//results/fwd-128/p-rec-forward.txt -data_comp_path  -data_comp_dat_path  -init_tumor_path  -model 4 -smooth 1 -observation_threshold -0.99 -k_gm_wm 0.0 -r_gm_wm 0.0 -low_freq_noise 0.0 -prediction 0 -forward 0 -order 2 -verbosity 1 -forcing_factor 0.0 -kappa_lb 0.05 -kappa_ub 0.5 -tao_lmm_vectors 50 -tao_lmm_scale_type broyden -tao_lmm_scalar_history 5 -tao_lmm_rescale_type scalar -tao_lmm_rescale_history 5  -tumor_tao_ls_max_funcs 10 